language: node_js
node_js:
  - 0.10
before_install:
  - git clone "https://github.com/davedoesdev/build-couchdb-travis.git"
  - ( cd build-couchdb-travis; wget -O - "https://github.com/davedoesdev/build-couchdb-travis/releases/download/$(git tag | tail -n 1)/build-couchdb.tar.gz" | tar -zxC .. )
  - ln -s build-couchdb ~
script: npm run travis-test
