language: node_js
node_js:
  - 0.10
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y help2man make gcc zlib1g-dev libssl-dev rake texinfo flex dctrl-tools libsctp-dev libxslt1-dev libcap2-bin ed
  - couchdb/build_couchdb.sh
script: npm run travis-test
