dist: bionic
language: node_js
node_js:
  - 10
  - 12
  - 14
env:
  - TEST_TYPE=test
  - TEST_TYPE=cover
services:
  - postgresql
before_install:
  - ( cd ..; git clone "https://github.com/davedoesdev/build-couchdb-travis.git"; cd build-couchdb-travis; wget -O - "https://github.com/davedoesdev/build-couchdb-travis/releases/download/$(git tag | tail -n 1)/couchdb.tar.gz" | tar -zx; ln -s "$PWD/couchdb" "$HOME" )
  - ls -l --color=always "$HOME/couchdb/rel/couchdb/bin"
before_script:
  - psql -c 'create database "pub-keystore";'
  - npm run pg-migrate
script: ./.travis.sh
